version: '2'

volumes:
  postgres_data: {}
  static_files: {}

services:
  postgres:
    env_file: .env
    environment:
      - POSTGRES_USER=apostello
      - POSTGRES_PASSWORD=apostello
    image: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups/postgres:/backups
    restart: always
  redis:
    image: redis
    restart: always
  q:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_prod
    command: bash -c "./manage.py setup_periodic_tasks && ./manage.py qcluster"
    depends_on:
      - postgres
      - redis
    restart: always
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_prod
    command: ./gunicorn.sh
    volumes:
      - static_files:/code/static/
    depends_on:
      - postgres
      - redis
    restart: always
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_files:/apostello/static/
    depends_on:
      - django
    restart: always
